name: 'Thanks a pull request'

on:
  pull_request_target:
    types: 
      - opened
    branches: 
      - 'main'

jobs:
  thanks-pr-message:
    runs-on: ubuntu-latest
    steps:
      - name: Thanks PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello there, thanks for opening your Pull Request. Someone will review it soon.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}